package test;


public class ProjectInitializer {
	
	/*
INSERT INTO WORKPLACE VALUES(1,"GENT");
INSERT INTO WORKPLACE VALUES(2,"OOSTENDE");	 
INSERT INTO WORKPLACE VALUES(3,"BRUGGE");
INSERT INTO TRAINCOACH VALUES(1,"Harry Potter","WagonXEZ","LHKD70");
INSERT INTO TRAINCOACH VALUES(2,"John Lee","WagonVLKJ","LHKD70");
INSERT INTO WORKPLACE_TRAINCOACH VALUES(1,1);
INSERT INTO WORKPLACE_TRAINCOACH VALUES(1,2);
INSERT INTO WORKPLACE_TRAINCOACH VALUES(2,1);
INSERT INTO WORKPLACE_TRAINCOACH VALUES(2,2);
INSERT INTO 
	 

	
	 */
	
}
